In [20]:
import numpy as np
import pandas as pd

appts = pd.read_csv('/Users/gary/Desktop/05012016_07312016_FAM_A3.csv')
appts['MRN'] = appts['MRN'].astype(str)
appts['MRN'] = appts['MRN'].str.zfill(8)
appts

,MRN,contact_date,appt_time,department_name,visit_prov,pat_first_name,pat_last_name,birth_date,ethnic_grp,race_1,sex
0,24432312,5/20/16,10:30:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Mattie,Westbrook,11/2/21,Non-Hispanic,Black,F
1,11962339,5/20/16,10:15:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Gloria,Bertholf,2/16/49,Non-Hispanic,Black,F
2,19757483,5/20/16,9:00:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Derrick,Cox,2/19/50,Non-Hispanic,Black,M
3,20958096,5/20/16,11:00:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Sally,Jordan,7/11/46,Unknown (Patient cannot or refuses to declare ...,White,F
4,23858087,5/20/16,8:00:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Maryjean,Zampino,8/15/64,Non-Hispanic,White,F
5,30228645,5/20/16,7:30:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Rosalind,Chaplin,4/22/87,Non-Hispanic,White,F
6,07334378,5/20/16,9:30:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Emma,Patton,5/4/33,Non-Hispanic,White,F
7,10930980,5/20/16,7:45:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Laura,Schreibman,9/8/46,Non-Hispanic,White,F
8,12236501,5/20/16,8:30:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Patricia,Nelson,5/5/51,Non-Hispanic,White,F
9,12620712,5/20/16,9:15:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",SARA,FRALEIGH,5/5/48,Non-Hispanic,White,F
10,13776364,5/20/16,11:00:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Karen,Coleman,10/25/41,Non-Hispanic,White,F
11,17123571,5/20/16,8:15:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Tara,Sweeney,6/1/70,Non-Hispanic,White,F
12,17537713,5/20/16,10:00:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Richard,Buss,5/29/46,Non-Hispanic,White,M
13,19420603,5/20/16,10:30:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Marianne,Yates,5/11/53,Non-Hispanic,White,F
14,25991530,5/20/16,8:30:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Larry,Hogan,1/29/50,Non-Hispanic,White,M
15,26187690,5/20/16,9:30:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Odette,Mikhail,1/2/34,Non-Hispanic,White,F
16,30065805,5/20/16,7:15:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Michael,Nee,3/19/51,Non-Hispanic,White,M
17,30160589,5/20/16,11:45:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Shirley,Sandler,9/24/31,Non-Hispanic,White,F
18,07450356,5/23/16,14:15:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Helen,Doakes,2/22/49,Non-Hispanic,Black,F
19,13468855,5/23/16,9:30:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Gwendolyn,Stovall,12/11/41,Non-Hispanic,Black,F
20,30041535,5/23/16,14:00:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Donna,Garrett,5/1/51,Non-Hispanic,Black,F
21,22637151,5/23/16,13:15:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",LAWRENCE,GOLDSTEIN,1/23/46,Non-Hispanic,White,M
22,23620735,5/23/16,9:00:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Eleanor,Buckley,6/20/37,Non-Hispanic,White,F
23,25283102,5/23/16,8:15:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Mark,Watson,6/8/61,Non-Hispanic,White,M
24,25653064,5/23/16,11:30:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Walter,Seymour,1/20/40,Non-Hispanic,White,M
25,08583643,5/23/16,9:30:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Judith,Faitek,11/13/45,Non-Hispanic,White,F
26,08691859,5/23/16,13:15:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Tex,Xelowski,2/24/51,Non-Hispanic,White,M
27,11104577,5/23/16,10:00:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Jerilyn,Millard,6/30/47,Hispanic,White,F
28,11387495,5/23/16,10:45:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Cynthia,Haddow,11/11/52,Non-Hispanic,White,F
29,13887161,5/23/16,14:15:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Larry,Haskins,3/15/48,Non-Hispanic,White,M
...,...,...,...,...,...,...,...,...,...,...,...
212,10922383,7/8/16,8:00:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Theodore,Witte,12/30/44,Non-Hispanic,White,M
213,26381830,7/8/16,10:30:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Ann,Harrington,3/1/37,Non-Hispanic,White,F
214,30112480,7/8/16,10:00:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Marvin,Ruebel,7/16/33,Non-Hispanic,White,M
215,05381785,7/11/16,13:30:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Kurt,Shuler,7/10/22,Unknown (Patient cannot or refuses to declare ...,White,M
216,22083653,7/11/16,14:00:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Evi,Quinn,5/4/28,Non-Hispanic,White,F
217,22238398,7/11/16,9:30:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Stephanie,Souviney,8/30/51,Non-Hispanic,White,F
218,23682024,7/11/16,10:00:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Richard,McDowell,3/21/45,Non-Hispanic,White,M
219,24614554,7/11/16,10:30:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Florine,Sprung,2/11/34,Non-Hispanic,White,F
220,24719643,7/11/16,10:30:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Christian,Julien,9/24/38,Non-Hispanic,White,M
221,25223744,7/11/16,9:30:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Clarita,Woodworth,9/22/27,Non-Hispanic,White,F
222,07793839,7/11/16,10:00:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Charles,Berry,7/30/46,Non-Hispanic,White,M
223,08893489,7/11/16,13:00:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Jan,Kvandal,5/7/50,Non-Hispanic,White,F
224,10011781,7/11/16,11:00:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Joy,Frieman,1/20/28,Non-Hispanic,White,F
225,17840042,7/11/16,9:00:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Richard,Reynolds,12/8/37,Non-Hispanic,White,M
226,30095795,7/11/16,8:30:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",John,Sankis,10/31/49,Non-Hispanic,White,M
227,30096363,7/11/16,8:00:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Raymond,Aller,11/24/50,Non-Hispanic,White,M
228,23006703,7/22/16,11:15:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Pamela,Reilly,8/11/60,Non-Hispanic,White,F
229,25673369,7/22/16,9:30:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Del,Vogel,1/29/52,Non-Hispanic,White,M
230,30215925,7/22/16,10:30:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Gary,Goins,6/5/52,Non-Hispanic,White,M
231,14277875,7/22/16,11:00:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Lamartine,McDowell,12/6/31,Non-Hispanic,White,F
232,16302341,7/22/16,9:00:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Ursula,BellugiKlima,2/21/31,Non-Hispanic,White,F
233,17439803,7/22/16,9:30:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Nancy,Cunningham,3/12/51,Non-Hispanic,White,F
234,30112678,7/22/16,11:00:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Arlene,Way,3/1/35,Non-Hispanic,White,F
235,25444035,7/25/16,11:00:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Mary,Nolan,4/2/30,Non-Hispanic,White,F
236,26082636,7/25/16,9:00:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Joyloraine,Wilson,11/25/36,Non-Hispanic,White,F
237,26941708,7/25/16,10:00:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Ruth,Segal,5/28/38,Non-Hispanic,White,F
238,22608012,7/29/16,9:30:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Margaret,Bezy,7/28/42,Unknown (Patient cannot or refuses to declare ...,White,F
239,07265051,7/29/16,10:30:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Joan,Smith,11/5/31,Non-Hispanic,White,F
240,15093875,7/29/16,8:00:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",David,Forbes,7/29/38,Non-Hispanic,White,M
241,16768707,7/29/16,8:30:00,SHI OPHTHALMOLOGY,"MEDEIROS, FELIPE D",Ronnie,Kelly,9/22/70,Non-Hispanic,White,M

In [21]:
a3 = pd.read_csv('/Users/gary/desktop/query_result.csv', na_filter=False)
a3['ucsd_mrn'] = a3['ucsd_mrn'].astype(str)
a3['ucsd_mrn'] = a3['ucsd_mrn'].str.zfill(8)
a3

      ucsd_mrn  firstname   lastname         dob
0     19244672      LOREN   THOMPSON  1946-10-25
1     19244672      LOREN   THOMPSON  1946-10-25
2     00000000       JOHN        DOE  1900-01-04
3     00000000       JOHN        DOE  1900-01-04
4     00000000       JOHN        DOE  1900-01-04
5     00000000       JOHN        DOE  1900-01-04
6     00000000                        1900-01-01
7     00000000                        1900-01-01
8     00000000                        1900-01-01
9     00000000                        1900-01-01
10    00000000                        1900-01-01
11    00000000                        1900-01-01
12    00000000                        1900-01-01
13    00000000                        1905-01-01
14    00000000                        1963-11-01
15    00000000                        1956-01-01
16    00000000                        1963-02-24
17    00000000                        1960-07-23
18    00000000                        1932-01-15
19    00000000                        1932-01-15
20    21884382      HARRY    MATHEWS  1954-01-14
21    21884382      HARRY    MATHEWS  1954-01-14
22    00000000                        1951-10-10
23    00000000                        1949-03-25
24    00000000                        1941-06-28
25    00000000                        1950-08-20
26    00000000                        1936-02-23
27    00000000                        1934-04-08
28    00000000                        1938-12-26
29    00000000                        1950-08-18
...        ...        ...        ...         ...
4636  00000000                        1950-05-12
4637  12412920      AGNES      SWEET  1921-04-18
4638  30006974       PAUL     MENARD  1937-02-18
4639  00000000                        1956-05-27
4640  00000000                        1943-11-13
4641  00000000                        1964-12-21
4642  00000000                        1941-10-11
4643  00000000                        1951-06-28
4644  00000000                        1953-07-12
4645  21695036       JOSE     ORTEGA  1936-03-05
4646  30227155      NANCY  HARASCIUK  1943-09-29
4647  15594807      MAJID     NAFICY  1961-05-21
4648  00000000                        1925-11-15
4649  23790728    GREGORY      DOYLE  1963-03-14
4650  30211554   MARICELA   RENTERIA  1965-03-02
4651  22935225       ESAO     SUMIDA  1938-06-14
4652  00000000                        1945-08-12
4653  00000000                        1939-07-28
4654  24018798       JEAN    HAMMERL  1944-02-16
4655  25922592  PRISCILLA      LAMAR  1933-02-25
4656  16274052     LONNIE     MILLER  1949-06-21
4657  22782577      STEVE     ANGIUS  1950-01-15
4658  30232874  PRISCILLA      LAMAR  1954-12-06
4659  14345854   VIRGINIA   CORONADO  1951-06-05
4660  19891670    KENNETH    RITCHIE  1944-11-05
4661  18013425   TYNGHUEI       LIOU  1962-12-30
4662  00000000                        1967-06-28
4663  26358002   PATRICIA    BUDZIEN  1942-12-06
4664  17000480      JAMES   TROUTMAN  1957-07-01
4665  22077986      BRETT      COHEN  1969-03-28

[4666 rows x 4 columns]

In [19]:
needs_blood = appts[~appts['MRN'].isin(a3.ucsd_mrn)]

In [ ]:
needs_blood.to_csv('/Users/gary/desktop/possible_FAM_A3_05172016.csv', index=False)